### ISSUE TITLE
Dont show a date place if there is "CLOSED" in the description

### ISSUE THREAD

**Issue by eddiedsitt** [Janteby1/date_abase2#1]
lets find a way to skip any CLOSED places in our search results, or possibly gray it out so we can differentiate between closed and opened date places

**Comment by Janteby1** [comment]
Fixed. Now says location closed when you get the results BUT it only works if the notes of the date say CLOSED. that is the only indicator for closed I found in the db

**Comment by eddiedsitt** [comment]
Perfect. I gotta familiarize myself with this repo
